/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Option = IDL.Record({
  'optionImage' : IDL.Opt(IDL.Text),
  'optionText' : IDL.Opt(IDL.Text),
});
export const Subject = IDL.Variant({
  'maths' : IDL.Null,
  'chemistry' : IDL.Null,
  'physics' : IDL.Null,
});
export const ClassLevel = IDL.Variant({
  'class11th' : IDL.Null,
  'class12th' : IDL.Null,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'subject' : Subject,
  'explanation' : IDL.Opt(IDL.Text),
  'questionImage' : IDL.Opt(IDL.Text),
  'questionText' : IDL.Opt(IDL.Text),
  'correctAnswerIndex' : IDL.Nat,
  'classLevel' : ClassLevel,
  'options' : IDL.Vec(Option),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ChapterWiseTestDetails = IDL.Record({
  'testName' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'questions' : IDL.Vec(Question),
  'marksPerQuestion' : IDL.Nat,
});
export const TestSection = IDL.Record({
  'subjects' : IDL.Vec(Subject),
  'name' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'questionIds' : IDL.Vec(IDL.Nat),
  'marksPerQuestion' : IDL.Nat,
});
export const FullSyllabusTest = IDL.Record({
  'createdAt' : IDL.Int,
  'testName' : IDL.Text,
  'isActive' : IDL.Bool,
  'section1' : TestSection,
  'section2' : TestSection,
  'testId' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'userName' : IDL.Text,
  'rank' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'totalTimeTaken' : IDL.Int,
});
export const Answer = IDL.Record({
  'selectedOptionIndex' : IDL.Nat,
  'questionId' : IDL.Nat,
});
export const TestAttempt = IDL.Record({
  'section2SubmittedAt' : IDL.Opt(IDL.Int),
  'section1Score' : IDL.Nat,
  'attemptId' : IDL.Nat,
  'isCompleted' : IDL.Bool,
  'section1StartTime' : IDL.Opt(IDL.Int),
  'singleSectionSubmittedAt' : IDL.Opt(IDL.Int),
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'section1Answers' : IDL.Vec(Answer),
  'currentSection' : IDL.Nat,
  'section2Score' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'totalTimeTaken' : IDL.Int,
  'section2Answers' : IDL.Vec(Answer),
  'section1SubmittedAt' : IDL.Opt(IDL.Int),
  'singleSectionScore' : IDL.Nat,
  'testId' : IDL.Nat,
  'completionTimestamp' : IDL.Int,
  'singleSectionStartTime' : IDL.Opt(IDL.Int),
  'singleSectionAnswers' : IDL.Vec(Answer),
  'section2StartTime' : IDL.Opt(IDL.Int),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignQuestionsToChapterWiseTest' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Nat)],
      [],
      [],
    ),
  'assignQuestionsToTest' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Nat), IDL.Vec(IDL.Nat)],
      [],
      [],
    ),
  'createChapterWiseTest' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createFullSyllabusTest' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createQuestion' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Vec(Option),
        IDL.Nat,
        IDL.Opt(IDL.Text),
        Subject,
        ClassLevel,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChapterWiseTestById' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Variant({
          'ok' : ChapterWiseTestDetails,
          'testNotFound' : IDL.Null,
        }),
      ],
      ['query'],
    ),
  'getCurrentTestId' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
  'getFullSyllabusTests' : IDL.Func([], [IDL.Vec(FullSyllabusTest)], ['query']),
  'getLeaderboard' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getQuestion' : IDL.Func([IDL.Nat], [IDL.Opt(Question)], ['query']),
  'getQuestionsByClassLevel' : IDL.Func(
      [ClassLevel],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getQuestionsBySubject' : IDL.Func([Subject], [IDL.Vec(Question)], ['query']),
  'getTestAttempt' : IDL.Func([IDL.Nat], [IDL.Opt(TestAttempt)], ['query']),
  'getTotalQuestions' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTestAttempts' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TestAttempt)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startSection' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'startTest' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'submitSection' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Vec(Answer)],
      [IDL.Record({ 'score' : IDL.Nat, 'correctAnswers' : IDL.Nat })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Option = IDL.Record({
    'optionImage' : IDL.Opt(IDL.Text),
    'optionText' : IDL.Opt(IDL.Text),
  });
  const Subject = IDL.Variant({
    'maths' : IDL.Null,
    'chemistry' : IDL.Null,
    'physics' : IDL.Null,
  });
  const ClassLevel = IDL.Variant({
    'class11th' : IDL.Null,
    'class12th' : IDL.Null,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'subject' : Subject,
    'explanation' : IDL.Opt(IDL.Text),
    'questionImage' : IDL.Opt(IDL.Text),
    'questionText' : IDL.Opt(IDL.Text),
    'correctAnswerIndex' : IDL.Nat,
    'classLevel' : ClassLevel,
    'options' : IDL.Vec(Option),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ChapterWiseTestDetails = IDL.Record({
    'testName' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'questions' : IDL.Vec(Question),
    'marksPerQuestion' : IDL.Nat,
  });
  const TestSection = IDL.Record({
    'subjects' : IDL.Vec(Subject),
    'name' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'questionIds' : IDL.Vec(IDL.Nat),
    'marksPerQuestion' : IDL.Nat,
  });
  const FullSyllabusTest = IDL.Record({
    'createdAt' : IDL.Int,
    'testName' : IDL.Text,
    'isActive' : IDL.Bool,
    'section1' : TestSection,
    'section2' : TestSection,
    'testId' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'userName' : IDL.Text,
    'rank' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'totalTimeTaken' : IDL.Int,
  });
  const Answer = IDL.Record({
    'selectedOptionIndex' : IDL.Nat,
    'questionId' : IDL.Nat,
  });
  const TestAttempt = IDL.Record({
    'section2SubmittedAt' : IDL.Opt(IDL.Int),
    'section1Score' : IDL.Nat,
    'attemptId' : IDL.Nat,
    'isCompleted' : IDL.Bool,
    'section1StartTime' : IDL.Opt(IDL.Int),
    'singleSectionSubmittedAt' : IDL.Opt(IDL.Int),
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'section1Answers' : IDL.Vec(Answer),
    'currentSection' : IDL.Nat,
    'section2Score' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'totalTimeTaken' : IDL.Int,
    'section2Answers' : IDL.Vec(Answer),
    'section1SubmittedAt' : IDL.Opt(IDL.Int),
    'singleSectionScore' : IDL.Nat,
    'testId' : IDL.Nat,
    'completionTimestamp' : IDL.Int,
    'singleSectionStartTime' : IDL.Opt(IDL.Int),
    'singleSectionAnswers' : IDL.Vec(Answer),
    'section2StartTime' : IDL.Opt(IDL.Int),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignQuestionsToChapterWiseTest' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat)],
        [],
        [],
      ),
    'assignQuestionsToTest' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat), IDL.Vec(IDL.Nat)],
        [],
        [],
      ),
    'createChapterWiseTest' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createFullSyllabusTest' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createQuestion' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Vec(Option),
          IDL.Nat,
          IDL.Opt(IDL.Text),
          Subject,
          ClassLevel,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChapterWiseTestById' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Variant({
            'ok' : ChapterWiseTestDetails,
            'testNotFound' : IDL.Null,
          }),
        ],
        ['query'],
      ),
    'getCurrentTestId' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
    'getFullSyllabusTests' : IDL.Func(
        [],
        [IDL.Vec(FullSyllabusTest)],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getQuestion' : IDL.Func([IDL.Nat], [IDL.Opt(Question)], ['query']),
    'getQuestionsByClassLevel' : IDL.Func(
        [ClassLevel],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getQuestionsBySubject' : IDL.Func(
        [Subject],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getTestAttempt' : IDL.Func([IDL.Nat], [IDL.Opt(TestAttempt)], ['query']),
    'getTotalQuestions' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTestAttempts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TestAttempt)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startSection' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'startTest' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'submitSection' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Vec(Answer)],
        [IDL.Record({ 'score' : IDL.Nat, 'correctAnswers' : IDL.Nat })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };