/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ClassLevel = { 'class11th' : null } |
  { 'class12th' : null };
export interface FullSyllabusTest {
  'createdAt' : bigint,
  'testName' : string,
  'isActive' : boolean,
  'section1' : TestSection,
  'section2' : TestSection,
  'testId' : bigint,
}
export interface Option {
  'optionImage' : [] | [string],
  'optionText' : [] | [string],
}
export interface Question {
  'id' : bigint,
  'subject' : Subject,
  'explanation' : string,
  'questionImage' : [] | [string],
  'questionText' : [] | [string],
  'correctAnswerIndex' : bigint,
  'classLevel' : ClassLevel,
  'options' : Array<Option>,
}
export type Subject = { 'maths' : null } |
  { 'chemistry' : null } |
  { 'physics' : null };
export interface TestSection {
  'subjects' : Array<Subject>,
  'name' : string,
  'durationMinutes' : bigint,
  'questionIds' : Array<bigint>,
  'marksPerQuestion' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignQuestionsToTest' : ActorMethod<
    [bigint, Array<bigint>, Array<bigint>],
    undefined
  >,
  'createFullSyllabusTest' : ActorMethod<[string], bigint>,
  'createQuestion' : ActorMethod<
    [
      [] | [string],
      [] | [string],
      Array<Option>,
      bigint,
      string,
      Subject,
      ClassLevel,
    ],
    bigint
  >,
  'deleteQuestion' : ActorMethod<[bigint], undefined>,
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentTestId' : ActorMethod<[], [] | [bigint]>,
  'getFullSyllabusTests' : ActorMethod<[], Array<FullSyllabusTest>>,
  'getQuestion' : ActorMethod<[bigint], [] | [Question]>,
  'getQuestionsByClassLevel' : ActorMethod<[ClassLevel], Array<Question>>,
  'getQuestionsBySubject' : ActorMethod<[Subject], Array<Question>>,
  'getTotalQuestions' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startTest' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];