/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface FullSyllabusTest {
    createdAt: bigint;
    testName: string;
    isActive: boolean;
    section1: TestSection;
    section2: TestSection;
    testId: bigint;
}
export interface Answer {
    selectedOptionIndex: bigint;
    questionId: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface TestSection {
    subjects: Array<Subject>;
    name: string;
    durationMinutes: bigint;
    questionIds: Array<bigint>;
    marksPerQuestion: bigint;
}
export interface Option {
    optionImage?: string;
    optionText?: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Question {
    id: bigint;
    subject: Subject;
    explanation: string;
    questionImage?: string;
    questionText?: string;
    correctAnswerIndex: bigint;
    classLevel: ClassLevel;
    options: Array<Option>;
}
export interface UserProfile {
    name: string;
}
export interface TestAttempt {
    section2SubmittedAt?: bigint;
    section1Score: bigint;
    attemptId: bigint;
    isCompleted: boolean;
    section1StartTime?: bigint;
    userId: Principal;
    createdAt: bigint;
    section1Answers: Array<Answer>;
    currentSection: bigint;
    section2Score: bigint;
    section2Answers: Array<Answer>;
    section1SubmittedAt?: bigint;
    testId: bigint;
    section2StartTime?: bigint;
}
export enum ClassLevel {
    class11th = "class11th",
    class12th = "class12th"
}
export enum Subject {
    maths = "maths",
    chemistry = "chemistry",
    physics = "physics"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignQuestionsToTest(testId: bigint, section1QuestionIds: Array<bigint>, section2QuestionIds: Array<bigint>): Promise<void>;
    createFullSyllabusTest(testName: string): Promise<bigint>;
    createQuestion(questionText: string | null, questionImage: string | null, options: Array<Option>, correctAnswerIndex: bigint, explanation: string, subject: Subject, classLevel: ClassLevel): Promise<bigint>;
    deleteQuestion(id: bigint): Promise<void>;
    getAllQuestions(): Promise<Array<Question>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentTestId(): Promise<bigint | null>;
    getFullSyllabusTests(): Promise<Array<FullSyllabusTest>>;
    getQuestion(id: bigint): Promise<Question | null>;
    getQuestionsByClassLevel(classLevel: ClassLevel): Promise<Array<Question>>;
    getQuestionsBySubject(subject: Subject): Promise<Array<Question>>;
    getTestAttempt(attemptId: bigint): Promise<TestAttempt | null>;
    getTotalQuestions(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserTestAttempts(userId: Principal): Promise<Array<TestAttempt>>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    startSection(attemptId: bigint, sectionNumber: bigint): Promise<void>;
    startTest(testId: bigint): Promise<void>;
    submitSection(attemptId: bigint, sectionNumber: bigint, answers: Array<Answer>): Promise<{
        score: bigint;
        correctAnswers: bigint;
    }>;
}
import type { Answer as _Answer, ClassLevel as _ClassLevel, FullSyllabusTest as _FullSyllabusTest, Option as _Option, Question as _Question, Subject as _Subject, TestAttempt as _TestAttempt, TestSection as _TestSection, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignQuestionsToTest(arg0: bigint, arg1: Array<bigint>, arg2: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignQuestionsToTest(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignQuestionsToTest(arg0, arg1, arg2);
            return result;
        }
    }
    async createFullSyllabusTest(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createFullSyllabusTest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFullSyllabusTest(arg0);
            return result;
        }
    }
    async createQuestion(arg0: string | null, arg1: string | null, arg2: Array<Option>, arg3: bigint, arg4: string, arg5: Subject, arg6: ClassLevel): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuestion(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), to_candid_vec_n11(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_Subject_n14(this._uploadFile, this._downloadFile, arg5), to_candid_ClassLevel_n16(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuestion(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), to_candid_vec_n11(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_Subject_n14(this._uploadFile, this._downloadFile, arg5), to_candid_ClassLevel_n16(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async deleteQuestion(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuestion(arg0);
            return result;
        }
    }
    async getAllQuestions(): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuestions();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuestions();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentTestId(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentTestId();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentTestId();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFullSyllabusTests(): Promise<Array<FullSyllabusTest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFullSyllabusTests();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFullSyllabusTests();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestion(arg0: bigint): Promise<Question | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestion(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestion(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestionsByClassLevel(arg0: ClassLevel): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionsByClassLevel(to_candid_ClassLevel_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionsByClassLevel(to_candid_ClassLevel_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestionsBySubject(arg0: Subject): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionsBySubject(to_candid_Subject_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionsBySubject(to_candid_Subject_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestAttempt(arg0: bigint): Promise<TestAttempt | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestAttempt(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestAttempt(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalQuestions(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalQuestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalQuestions();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTestAttempts(arg0: Principal): Promise<Array<TestAttempt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTestAttempts(arg0);
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTestAttempts(arg0);
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async startSection(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startSection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startSection(arg0, arg1);
            return result;
        }
    }
    async startTest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startTest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startTest(arg0);
            return result;
        }
    }
    async submitSection(arg0: bigint, arg1: bigint, arg2: Array<Answer>): Promise<{
        score: bigint;
        correctAnswers: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSection(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSection(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_ClassLevel_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClassLevel): ClassLevel {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_FullSyllabusTest_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FullSyllabusTest): FullSyllabusTest {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Option_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Option): Option {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Subject_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subject): Subject {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_TestAttempt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestAttempt): TestAttempt {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_TestSection_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestSection): TestSection {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Question]): Question | null {
    return value.length === 0 ? null : from_candid_Question_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TestAttempt]): TestAttempt | null {
    return value.length === 0 ? null : from_candid_TestAttempt_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    subject: _Subject;
    explanation: string;
    questionImage: [] | [string];
    questionText: [] | [string];
    correctAnswerIndex: bigint;
    classLevel: _ClassLevel;
    options: Array<_Option>;
}): {
    id: bigint;
    subject: Subject;
    explanation: string;
    questionImage?: string;
    questionText?: string;
    correctAnswerIndex: bigint;
    classLevel: ClassLevel;
    options: Array<Option>;
} {
    return {
        id: value.id,
        subject: from_candid_Subject_n21(_uploadFile, _downloadFile, value.subject),
        explanation: value.explanation,
        questionImage: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.questionImage)),
        questionText: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.questionText)),
        correctAnswerIndex: value.correctAnswerIndex,
        classLevel: from_candid_ClassLevel_n24(_uploadFile, _downloadFile, value.classLevel),
        options: from_candid_vec_n26(_uploadFile, _downloadFile, value.options)
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    optionImage: [] | [string];
    optionText: [] | [string];
}): {
    optionImage?: string;
    optionText?: string;
} {
    return {
        optionImage: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.optionImage)),
        optionText: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.optionText))
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdAt: bigint;
    testName: string;
    isActive: boolean;
    section1: _TestSection;
    section2: _TestSection;
    testId: bigint;
}): {
    createdAt: bigint;
    testName: string;
    isActive: boolean;
    section1: TestSection;
    section2: TestSection;
    testId: bigint;
} {
    return {
        createdAt: value.createdAt,
        testName: value.testName,
        isActive: value.isActive,
        section1: from_candid_TestSection_n35(_uploadFile, _downloadFile, value.section1),
        section2: from_candid_TestSection_n35(_uploadFile, _downloadFile, value.section2),
        testId: value.testId
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subjects: Array<_Subject>;
    name: string;
    durationMinutes: bigint;
    questionIds: Array<bigint>;
    marksPerQuestion: bigint;
}): {
    subjects: Array<Subject>;
    name: string;
    durationMinutes: bigint;
    questionIds: Array<bigint>;
    marksPerQuestion: bigint;
} {
    return {
        subjects: from_candid_vec_n37(_uploadFile, _downloadFile, value.subjects),
        name: value.name,
        durationMinutes: value.durationMinutes,
        questionIds: value.questionIds,
        marksPerQuestion: value.marksPerQuestion
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    section2SubmittedAt: [] | [bigint];
    section1Score: bigint;
    attemptId: bigint;
    isCompleted: boolean;
    section1StartTime: [] | [bigint];
    userId: Principal;
    createdAt: bigint;
    section1Answers: Array<_Answer>;
    currentSection: bigint;
    section2Score: bigint;
    section2Answers: Array<_Answer>;
    section1SubmittedAt: [] | [bigint];
    testId: bigint;
    section2StartTime: [] | [bigint];
}): {
    section2SubmittedAt?: bigint;
    section1Score: bigint;
    attemptId: bigint;
    isCompleted: boolean;
    section1StartTime?: bigint;
    userId: Principal;
    createdAt: bigint;
    section1Answers: Array<Answer>;
    currentSection: bigint;
    section2Score: bigint;
    section2Answers: Array<Answer>;
    section1SubmittedAt?: bigint;
    testId: bigint;
    section2StartTime?: bigint;
} {
    return {
        section2SubmittedAt: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.section2SubmittedAt)),
        section1Score: value.section1Score,
        attemptId: value.attemptId,
        isCompleted: value.isCompleted,
        section1StartTime: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.section1StartTime)),
        userId: value.userId,
        createdAt: value.createdAt,
        section1Answers: value.section1Answers,
        currentSection: value.currentSection,
        section2Score: value.section2Score,
        section2Answers: value.section2Answers,
        section1SubmittedAt: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.section1SubmittedAt)),
        testId: value.testId,
        section2StartTime: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.section2StartTime))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maths: null;
} | {
    chemistry: null;
} | {
    physics: null;
}): Subject {
    return "maths" in value ? Subject.maths : "chemistry" in value ? Subject.chemistry : "physics" in value ? Subject.physics : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    class11th: null;
} | {
    class12th: null;
}): ClassLevel {
    return "class11th" in value ? ClassLevel.class11th : "class12th" in value ? ClassLevel.class12th : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Option>): Array<Option> {
    return value.map((x)=>from_candid_Option_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FullSyllabusTest>): Array<FullSyllabusTest> {
    return value.map((x)=>from_candid_FullSyllabusTest_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Subject>): Array<Subject> {
    return value.map((x)=>from_candid_Subject_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TestAttempt>): Array<TestAttempt> {
    return value.map((x)=>from_candid_TestAttempt_n40(_uploadFile, _downloadFile, x));
}
function to_candid_ClassLevel_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassLevel): _ClassLevel {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Option_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Option): _Option {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Subject_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject): _Subject {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    optionImage?: string;
    optionText?: string;
}): {
    optionImage: [] | [string];
    optionText: [] | [string];
} {
    return {
        optionImage: value.optionImage ? candid_some(value.optionImage) : candid_none(),
        optionText: value.optionText ? candid_some(value.optionText) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject): {
    maths: null;
} | {
    chemistry: null;
} | {
    physics: null;
} {
    return value == Subject.maths ? {
        maths: null
    } : value == Subject.chemistry ? {
        chemistry: null
    } : value == Subject.physics ? {
        physics: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassLevel): {
    class11th: null;
} | {
    class12th: null;
} {
    return value == ClassLevel.class11th ? {
        class11th: null
    } : value == ClassLevel.class12th ? {
        class12th: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Option>): Array<_Option> {
    return value.map((x)=>to_candid_Option_n12(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
